### ISSUE TITLE
Implementation for macOS target?

### ISSUE THREAD

**Issue by vasilenkoigor** [rambler-ios/ViperMcFlurry#31]
Hey, guys! 

How about an implementation of a framework for macOS target? I'll suggest that it's easy to implement this feature. Also, I can try this and make PR.

**Comment by etolstoy** [comment]
Hi, @vasilenkoigor! I'll be glad to accept your PR.

**Comment by vasilenkoigor** [comment]
Hi, @etolstoy! Glad to see you. Ok, I'll try to do this on this weekends.

**Comment by RomanTruba** [comment]
@vasilenkoigor if you still interested in, I've made an implementation of this lib for macOS with example, but it also requires special Typhoon osx version (support osx storyboards) in my repo.
I haven't created a pull request with this code, because I think it will be rejected, but you can try working with it.
See https://github.com/RomanTruba/ViperMcFlurry/tree/osx-version , https://github.com/RomanTruba/Typhoon/tree/mac-storyboard-support
